### PR TITLE
Fixed auto fire infinite ammo

### LINKED ISSUE #456: [Bug]: unlimited ammo in autofire mode for some guns
### Confirmations

- [X] I am using the latest plugin version with the required dependencies.
- [X] There isn't any open issue that shows my problem

### What happened?

when using the glock on the mp5k on auto fire mode or like scoping in, it doesn't use up ammo.

using latest qa version

### Expected Behaviour

for it to use up ammo

### Plugins

na

### Server Version

1.19.2

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by zimzaza4**
Fixed #456 #495

### CODE REVIEW

**Comment by ZombieStriker** [comment]
This looks good. I was originally working on a prototype rewrite of this, but this should be good for now to fix those bugs. Once @Lorenzo0111 approves of the merge, we can merge and release a new path for QA.

**Review by ZombieStriker — APPROVED** [review]
Looks fine.

**Comment by Lorenzo0111** [comment]
I think I already applied another workaround to fix the same issue. Could you test with this [dev build?](https://to.lorenzo0111.me/qadev)
If the issue will persist I'll approve this.

**Comment by zimzaza4** [comment]
Oh I tested it, you fixed the problem

**Comment by zimzaza4** [comment]
so i can close this pr?

**Comment by BEWARETHEDEAD** [comment]
the bug with infinite cartridges is still present when you shoot from the hip from any automatic weapon - everything is fine, but if you start shooting in the sight, the cartridges are endless.

**Comment by zimzaza4** [comment]
> the bug with infinite cartridges is still present when you shoot from the hip from any automatic weapon - everything is fine, but if you start shooting in the sight, the cartridges are endless.

you are using his build? or this pr's

**Comment by BEWARETHEDEAD** [comment]
im tryied to use this - https://to.lorenzo0111.me/qadev

**Comment by zimzaza4** [comment]
> im tryied to use this - https://to.lorenzo0111.me/qadev

try this (this pr's build)
[QualityArmory-TEST.zip](https://github.com/ZombieStriker/QualityArmory/files/12840751/QualityArmory-TEST.zip)

**Comment by zimzaza4** [comment]
WAIT I gave a wrong build

**Comment by zimzaza4** [comment]
ok, try this
[QualityArmory.zip](https://github.com/ZombieStriker/QualityArmory/files/12840774/QualityArmory.zip)

**Comment by BEWARETHEDEAD** [comment]
> > the bug with infinite cartridges is still present when you shoot from the hip from any automatic weapon - everything is fine, but if you start shooting in the sight, the cartridges are endless.
> 
> you are using his build? or this pr's



> ok, try this [QualityArmory.zip](https://github.com/ZombieStriker/QualityArmory/files/12840774/QualityArmory.zip)

if you shoot from the hip there is no bug, if you shoot in the sight - there is

**Comment by zimzaza4** [comment]
wait I gave wrong build again sorry XP

**Comment by zimzaza4** [comment]
well, my problem, I didn't test it with a sniper rifle before

**Comment by zimzaza4** [comment]
OK now it's fixed
[QualityArmory.zip](https://github.com/ZombieStriker/QualityArmory/files/12840868/QualityArmory.zip)

**Comment by BEWARETHEDEAD** [comment]
> OK now it's fixed [QualityArmory.zip](https://github.com/ZombieStriker/QualityArmory/files/12840868/QualityArmory.zip)

ty, that working

**Comment by Lorenzo0111** [comment]
I'm not sure. Does my build work? @zimzaza4

**Comment by zimzaza4** [comment]
maybe non-automatic guns still have problem? ummm i don't have time to test it until the weekend

**Comment by Lorenzo0111** [comment]
> maybe non-automatic guns still have problem? ummm i don't have time to test it until the weekend

Did you have time to check? @zimzaza4

**Comment by zimzaza4** [comment]
oh i forgot this

**Comment by zimzaza4** [comment]
I tested your build, non-auto guns seem no problem. but minigun seem broken, it's cannot shoot when aim

**Comment by Lorenzo0111** [comment]
I think I already fixed it in another commit, I'll push it tomorrow

**Comment by Lorenzo0111** [comment]
The way you did that is just a workaround so I would prefer fixing the issue in its root

**Comment by Lorenzo0111** [comment]
#549 should also patch this

**Comment by zimzaza4** [comment]
Your fix seems to be a bit wrong, if reload while aiming, the reload doesn't work

**Comment by Lorenzo0111** [comment]
Thanks for your bug reporting! It should be fixed with c22b9085c8ad2ac6b9b6cbb23aba8d358268fa83
I'm sorry for not just merging it but the whole codebase handles the ammo in a certain way and handling it differently just on this part would be strange

**Comment by zimzaza4** [comment]
ok, thank you

**Pull request closed without merging**
